### ISSUE TITLE
opendlv-device-camera-v4l-multi:v0.0.7 is available and we should use the latest versions

### ISSUE THREAD

**Issue by chrberger** [chalmersfsd/cfsd-autonomous-system-usecases#2]
https://github.com/chalmers-revere/opendlv-device-camera-v4l/releases; important change for you: time stamping is improved

https://github.com/chalmersfsd/cfsd-autonomous-system-usecases/blob/1bbe19a2a395e37620ef0f52d708a6122a4ec154/sensors-test/basic_yml_file.yaml#L37-L51

**Comment by lowitz** [comment]
Version has been updated
