### ISSUE TITLE
opendlv-device-lidar-vlp16-multi:v0.0.10 is available and we should use the latest versions

### ISSUE THREAD

**Issue by chrberger** [chalmersfsd/cfsd-autonomous-system-usecases#3]
https://github.com/chalmers-revere/opendlv-device-lidar-vlp16/releases; important change for you: time stamping is possible using the GPS receiver; use `--gpstime` as command line flag to enable this feature after you have connected and configured the GPS receiver in Velodyne's web interface (check with Arpit in case of connection and configuration questions).

https://github.com/chalmersfsd/cfsd-autonomous-system-usecases/blob/1bbe19a2a395e37620ef0f52d708a6122a4ec154/sensors-test/basic_yml_file.yaml#L53-L59

**Comment by lowitz** [comment]
Version updated and added flag
